version: "3"

services:
  api:
    build: .
    depends_on:
      - grobid
    command: poetry run cli main
    restart: on-failure

  grobid:
    image: lfoppiano/grobid:0.7.0
    restart: always
    ports:
      - 8070:8070
      - 8071:8071
    volumes:
      - ./grobid.yaml:/opt/grobid/grobid-home/config/grobid.yaml