[tool.poetry]
name = "NLPLand"
version = "0.1.0"
description = ""
authors = ["Lennart Kuell <lennart.kuell@gmail.com>", "Jan Philip Wahle <wahle@uni-wuppertal.de>", "Terry Ruas <ruas@uni-wuppertal.de>"]

[tool.poetry.dependencies]
python = ">=3.7.1,<3.10"
torch="<=1.9.0"
click = "^7.0.1"
matplotlib = "^3.4.2"
numpy = "^1.20.3"
pandas = "^1.2.4"
python-dotenv = "^0.16"
tika = "^1.24"
tqdm = "^4.61.0"
urllib3 = "^1.26.4"
lxml = "^4.6.1"
nltk = "^3.6.2"
scikit-learn = "^0.24.2"
scattertext = "^0.1.2"
gensim = "^3.8.1"
pyLDAvis = "^3.3.1"
spacy = "^3.1.0"
llvmlite="^0.37.0"
umap-learn = {extras = ["plot"], version = "^0.5.1"}
en-core-web-sm = {url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.1.0/en_core_web_sm-3.1.0-py3-none-any.whl"}
en-core-web-trf = {url = "https://github.com/explosion/spacy-models/releases/download/en_core_web_trf-3.1.0/en_core_web_trf-3.1.0-py3-none-any.whl"}

[tool.poetry.dev-dependencies]
pytest = "^5.2"
pytest-cov = "^3.0.0"
black = "^21.9b0"
isort = "^5.9.3"
pyright = "^0.0.10"
pylint = "^2.11.1"
pytest-mock = "^3.6.1"

[tool.poetry.scripts]
cli = "nlpland.cli:cli"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
